name: First_workflow
on: 
  workflow_dispatch:
    inputs:
      env:
        description: 'environment to ingest to'
        required: true
        type: choice
        options:
          - dev
          - stage
          - prod
        default: 'dev'
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: echo "Hello World"
      - name: Goodbye
        run: |
          echo "See you later"
          echo "Printing multiple lines"
  checkout-job:
    env:
      DATABASE: ${{ secrets.DATABASE }}
      USERNAME: ${{ secrets.USERNAME }}
      TOKEN: ${{ secrets.TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set environment variables
        run: |
          if [ "${{ inputs.env }}" == "dev" ]; then
            echo "GMS_HOST=https://dev.com" >> $GITHUB_ENV
            echo "-----------"
            echo $GITHUB_ENV
          elif [ "${{ inputs.env }}" == "stage" ]; then
            echo "GMS_HOST=https://stage.com" >> $GITHUB_ENV
          elif [ "${{ inputs.env }}" == "prod" ]; then
            echo "GMS_HOST=https://prod.com" >> $GITHUB_ENV
          fi
      - name: initiate-script
        run: sh scripts/import.sh ${{ inputs.env }} $GITHUB_ENV 
      
