name: First_workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: echo "Hello World"
      - name: Goodbye
        run: |
          echo "See you later"
          echo "Printing multiple lines"
